name: Sync Football Schedule

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch: 


env:
  SEASON_NAME: "Spring_2026"
  SEASON_IDS: "S26"
  CURR_YEAR: "2026"
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: playwright install chromium --with-deps
        
      - name: Create Data Directory
        run: mkdir -p data

      - name: Run Scraper
        run: python src/scraper.py
        env:
          SEASON_NAME: ${{ env.SEASON_NAME }}
          SEASON_IDS: ${{ env.SEASON_IDS }}
          CURR_YEAR: ${{ env.CURR_YEAR }}

      - name: Run Parser
        run: python src/parser.py
        env:
          SEASON_NAME: ${{ env.SEASON_NAME }}
          SEASON_IDS: ${{ env.SEASON_IDS }}
          CURR_YEAR: ${{ env.CURR_YEAR }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # Reference the variable for the file path
          git add data/*.csv
          
          if git diff --staged --quiet; then
            echo "No changes to schedule detected. Skipping push."
          else
            git commit -m "Auto-update ${{ env.SEASON_NAME }}: $(date +'%Y-%m-%d %H:%M')"
            git push
          fi
          